export EDITOR=vim

alias dotfiles='cd ~/dotfiles'
alias bashrc="$EDITOR ~/dotfiles/config/bashrc"
alias bashr=bashrc
alias bashrl="$EDITOR ~/dotfiles/local/bashrc"
alias rebash='source ~/.bashrc'

source ~/dotfiles/config/bash/aliases.bash
source ~/dotfiles/config/bash/vim.bash
source ~/dotfiles/config/bash/git.bash
source ~/dotfiles/config/bash/rails.bash
source ~/dotfiles/config/bash/python.bash

# Display memory usage summary for a running process, refreshes every second.
# usage: memwatch pid
function memwatch() {
  watch -n 1 "vmmap $1 | tail -30"
}

# Source local/private customizations
# .gitignore contains an entry for dotfiles/local/
[[ -s ~/dotfiles/local/bashrc ]] && source ~/dotfiles/local/bashrc

[[ -s ~/.rvm/scripts/rvm ]] && source ~/.rvm/scripts/rvm  # This loads RVM into a shell session.
[[ -s /usr/local/sbin ]] && export PATH=$PATH:/usr/local/sbin
[[ -s $HOME/bin ]] && export PATH=$HOME/bin:$PATH
