export EDITOR=vim
export NODE_PATH=/usr/local/lib/node_modules

alias dotfiles='cd ~/dotfiles'
alias bashrc="$EDITOR ~/dotfiles/config/bashrc"
alias bashrl="$EDITOR ~/dotfiles/local/bashrc"
alias rebash='source ~/.bashrc'

function bashr() {
  if [ "$1" == "list" ]; then
    ls -1 ~/dotfiles/config/bash/*.bash
  elif [ $1 ]; then
    if [ -e ~/dotfiles/config/bash/$1.bash ]; then
      $EDITOR ~/dotfiles/config/bash/$1.bash
    else
      echo "Bash config for '$1' does not exist"
      ls -1 ~/dotfiles/config/bash/*.bash
    fi
  else
    bashrc
  fi
}

source ~/dotfiles/config/bash/aliases.bash
source ~/dotfiles/config/bash/vim.bash
source ~/dotfiles/config/bash/git-completion.bash
source ~/dotfiles/config/bash/git-prompt.bash
source ~/dotfiles/config/bash/ps1.bash
source ~/dotfiles/config/bash/grb.bash
source ~/dotfiles/config/bash/rails.bash
source ~/dotfiles/config/bash/python.bash

# Shortcut for symlinking a new dotfile after install
# usage: dotlink inputrc
function dotlink() {
  ln -s ~/dotfiles/config/$1 ~/.$1
}

# Display memory usage summary for a running process, refreshes every second.
# usage: memwatch pid
function memwatch() {
  watch -n 1 "vmmap $1 | tail -30"
}

# Source local/private customizations
# .gitignore contains an entry for dotfiles/local/
[[ -s ~/dotfiles/local/bashrc ]] && source ~/dotfiles/local/bashrc

[[ -s ~/.rvm/scripts/rvm ]] && source ~/.rvm/scripts/rvm  # This loads RVM into a shell session.
[[ -s /usr/local/sbin ]] && export PATH=$PATH:/usr/local/sbin
[[ -s $HOME/bin ]] && export PATH=$HOME/bin:$PATH
